on:
  push:
    branches:
      - master

name: Deploy to Amazon ECS

jobs:
  build:
    name: Create artifact
    runs-on: [ubuntu-18.04]
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1.1.0
        with:
          version: '12.x'

      - name: Build
        run: node lory build murder,deathrun prod
      
      - name: Create distributable
        run: mkdir dist && cp -R build dist && cp -R stateful dist && cp docker-compose.yaml dist
      
      - name: Upload artifact
        uses: actions/upload-artifact@v1.0.0
        with:
          name: Distributable
          path: dist
      
  deploy:
    name: Deploy
    runs-on: [ubuntu-18.04]
    steps:
    - name: SCP Command to Transfer Files
      uses: appleboy/scp-action@v0.0.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.RSA_KEY }}
        target: ~/dist
        source: dist
        rm: true
        overwrite: true
