name: Deploy ttt

on:
  push:
    branches: [ master ]
    paths:
      - 'servers/_shared/**'
      - 'servers/ttt/**'
      - '.github/workflows/ttt-deploy.yml'

jobs:
  build:
    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v1.1.0
      with:
        version: '12.x'

    - name: Build ttt
      run: |
        cd tool
        npm install
        node index ttt
        ls ../build

    - name: Upload addons artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: TTT
        path: build
   
  deploy:
    runs-on: ubuntu-18.04
    needs: [build]

    steps:
    - uses: actions/checkout@v2
    
    - name: Download addons
      uses: actions/download-artifact@v1.0.0
      with:
        name: TTT
        path: ttt

    - name: Upload addons
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.TTT_FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ttt
        git-ftp-args: --insecure --remote-root ./garrysmod/addons
